version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: 80
    env_file:
      - .env
    ####### Uncomment this block to start entrypoint manually
    # entrypoint:
    #   - tail
    #   - -f
    #   - /dev/null

networks:
  default:
    name: svd_network
